Repository apache/daffodil-vscode, pull requests merged in 2022-12, with the labels that each got.

#358 Fix typo, daffodilDebugClassPath -> daffodilDebugClasspath
  src/daffodilDebugger.ts
Labels: bug, javascript

#349 Add support for JSON formatting of infoset
  package.json
  server/core/src/main/scala/org.apache.daffodil.debugger.dap/Parse.scala
  src/adapter/activateDaffodilDebug.ts
  src/daffodil.ts
  src/infoset.ts
  src/launchWizard/launchWizard.js
  src/launchWizard/launchWizard.ts
  src/tests/suite/daffodil.test.ts
  src/tests/suite/utils.test.ts
  src/utils.ts
Labels: enhancement, scala, typescript

#379 Prepare 1.3.0-SNAPSHOT builds
  package.json
Labels: build

#371 omega-edit updates
  .gitignore
  build/package/.vscodeignore
  build/scripts/omega_edit_download.ts
  package.json
  src/daffodilDebugger.ts
  src/omega_edit/client.ts
  src/omega_edit/server.ts
  src/omega_edit/utils.ts
  src/tests/suite/omegaEdit.test.ts
  src/utils.ts
  yarn.lock
Labels: dependencies, typescript
