Repository apache/daffodil-vscode, pull requests merged in 2023-07, with the labels that each got.

#695 Add runtime jvm info to startup banner.
  debugger/src/main/scala/org.apache.daffodil.debugger.dap/DAPodil.scala
Labels: enhancement, scala

#694 Multiple debugger updates:
  debugger/src/main/resources/logback.xml
  package.json
  src/classes/vscode-launch.ts
  src/daffodilDebugger/debugger.ts
  src/daffodilDebugger/utils.ts
  src/tests/suite/daffodilDebugger.test.ts
  src/tests/suite/utils.test.ts
  src/utils.ts
  yarn.lock
Labels: typescript, debugger

#704 Multiple Launch Wizard updates
  src/classes/vscode-launch.ts
  src/launchWizard/launchWizard.js
  src/launchWizard/launchWizard.ts
  src/tests/suite/daffodilDebugger.test.ts
  src/tests/suite/utils.test.ts
  src/utils.ts
Labels: javascript, typescript, extension

#696 Relay parse assertion failures to debug console.
  debugger/src/main/scala/org.apache.daffodil.debugger.dap/Parse.scala
Labels: enhancement, debugger

#708 Multiple updates
  .gitignore
  .prettierignore
  README.md
  build/extension.webpack.config.js
  build/package/.vscodeignore
  build/scripts/package.ts
  build/yarn-scripts.ts
  debugger/nodemon.json
  package.json
  src/classes/artifact.ts
  src/daffodilDebugger/debugger.ts
  src/daffodilDebugger/utils.ts
  src/tests/suite/daffodilDebugger.test.ts
  src/utils.ts
  tsconfig.json
  webpack/ext-dev.webpack.config.js
  webpack/ext-package.webpack.config.js
  yarn.lock
Labels: enhancement, build, typescript, extension

#706 Un-normalize (capitalize) the drive letter from showOpenDialog if we are on Windows
  src/adapter/activateDaffodilDebug.ts
Labels: bug, TDML

#716 Multiple svelte updates:
  .prettierignore
  .prettierrc
  package.json
  src/svelte/.prettierrc
  src/svelte/package.json
  src/svelte/rollup.config.js
  src/svelte/src/components/dataEditor.svelte
  src/svelte/webpack.config.js
  src/svelte/yarn.lock
  webpack/ext-package.webpack.config.js
  yarn.lock
Labels: typescript

#699 Allow JVM reflection to fix JDK 17 changes.
  build.sbt
Labels: bug, debugger

#705 Semantic highlighting for XPath expressions
  LICENSE
  package.json
  src/adapter/activateDaffodilDebug.ts
  src/language/providers/attributeCompletion.ts
  src/language/providers/closeElement.ts
  src/language/providers/closeElementSlash.ts
  src/language/providers/elementCompletion.ts
  src/language/providers/utils.ts
  src/language/semantics/dfdlExt.ts
  src/language/semantics/documentChangeHandler.ts
  src/language/semantics/functionData.ts
  src/language/semantics/xPathDocumentChangeHandler.ts
  src/language/semantics/xpLexer.ts
  src/language/semantics/xslLexer.ts
  src/language/semantics/xsltTokenDiagnostics.ts
  yarn.lock
Labels: enhancement
