Repository apache/daffodil-vscode, pull requests merged in 2023-12, with the labels that each got.

#902 upgrade to Ωedit™ v0.9.76
  package.json
  yarn.lock
Labels: dependencies, data editor

#900 Added development.md
  DEVELOPMENT.md
Labels: documentation

#883 Implemented Indexable ByteValue Indications
  src/dataEditor/dataEditorClient.ts
  src/svelte/src/components/DataDisplays/CustomByteDisplay/DataLineFeed.svelte
  src/svelte/src/components/DataDisplays/CustomByteDisplay/DataValue.svelte
  src/svelte/src/components/DataDisplays/CustomByteDisplay/SelectedByteEdit.svelte
  src/svelte/src/components/DataDisplays/Header/DisplayHeader.svelte
  src/svelte/src/components/Header/fieldsets/FileMetrics.svelte
  src/svelte/src/components/Header/fieldsets/SearchReplace.svelte
  src/svelte/src/components/Header/fieldsets/SearchReplace.ts
  src/svelte/src/components/dataEditor.svelte
  src/svelte/src/components/globalStyles.css
  src/svelte/src/components/layouts/Tooltip.svelte
  src/svelte/src/stores/index.ts
  src/svelte/src/utilities/ByteCategories/CategoryIndications.ts
  src/svelte/src/utilities/ByteCategories/IByteCategory.ts
  src/svelte/src/utilities/ByteCategories/IIndication.ts
  src/svelte/src/utilities/display.ts
  src/svelte/src/utilities/highlights.ts
Labels: enhancement, typescript, data editor
