Repository apache/daffodil-vscode, pull requests merged in 2023-05, with the labels that each got.

#620 Launch wizard updates and rename data editor vars
  package.json
  src/adapter/activateDaffodilDebug.ts
  src/classes/dataEditor.ts
  src/classes/tdmlConfig.ts
  src/dataEdit/client.ts
  src/launchWizard/launchWizard.js
  src/launchWizard/launchWizard.ts
  src/tests/suite/daffodilDebugger.test.ts
  src/tests/suite/utils.test.ts
  src/utils.ts
Labels: bug, enhancement

#632 add Larry Barber as a Daffodil-VSCode collaborator
  .asf.yaml
Labels: documentation, configuration

#625 Add conditional defaults to TDML properties
  .vscode/launch.json
  package.json
  server/core/src/main/scala/org.apache.daffodil.debugger.dap/Parse.scala
  server/core/src/test/scala/org.apache.daffodil.debugger/ParseSuite.scala
  src/launchWizard/launchWizard.js
  src/launchWizard/launchWizard.ts
  src/tests/suite/daffodilDebugger.test.ts
  src/tests/suite/utils.test.ts
  src/utils.ts
Labels: typescript, configuration
