Repository apache/daffodil-vscode, pull requests merged in 2023-03, with the labels that each got.

#453 conditionally require wait_port
  src/tests/suite/omegaEdit.test.ts
  src/utils.ts
Labels: javascript, code quality

#253 Daffodil VsCode TDML
  .gitignore
  .vscode/launch.json
  build.sbt
  package.json
  project/Rat.scala
  project/plugins.sbt
  server/core/src/main/resources/bindings.xjb
  server/core/src/main/scala/org.apache.daffodil.debugger.dap/DAPodil.scala
  server/core/src/main/scala/org.apache.daffodil.debugger.dap/Parse.scala
  server/core/src/main/scala/org.apache.daffodil.debugger.dap/logging.scala
  server/core/src/main/scala/org.apache.daffodil.tdml/TDML.scala
  server/core/src/test/data/emptyData.xml
  server/core/src/test/data/emptyInfoset.xml
  server/core/src/test/data/emptySchema.dfdl.xsd
  server/core/src/test/data/notInfoset.xml
  server/core/src/test/scala/org.apache.daffodil.debugger/ParseSuite.scala
  server/core/src/test/scala/org.apache.daffodil.tdml/TDMLSuite.scala
  src/adapter/activateDaffodilDebug.ts
  src/daffodilDebugger.ts
  src/launchWizard/launchWizard.js
  src/launchWizard/launchWizard.ts
  src/tests/data/test.tdml
  src/tests/data/test.txt
  src/tests/data/test2.dfdl.xsd
  src/tests/data/txttest.dfdl.xsd
  src/tests/suite/common.ts
  src/tests/suite/daffodil.test.ts
  src/tests/suite/daffodilDebugger.test.ts
  src/tests/suite/utils.test.ts
  src/utils.ts
Labels: enhancement, help wanted, scala

#472 Change the behavior of inserting the format tag
  src/language/providers/attributeCompletion.ts
  src/language/providers/closeElement.ts
  src/language/providers/closeUtils.ts
  src/language/providers/elementCompletion.ts
  src/language/providers/intellisense/attributeItems.ts
  src/language/providers/intellisense/commonItems.ts
  src/language/providers/intellisense/elementItems.ts
  src/language/providers/utils.ts
  src/tests/suite/language/items.test.ts
Labels: bug, enhancement, javascript

#415 allow workflow dispatch on nightly tests
  .github/workflows/nightly.yml
Labels: testing, CI

#490 upgraded omega-edit to v0.9.55 and removed pino dependency
  package.json
  yarn.lock
Labels: bug, dependencies

#496 Scala tests are ran during yarn test. Remove sbt test from CI.
  .github/workflows/CI.yml
  .github/workflows/nightly.yml
  package.json
Labels: bug, testing, CI

#500 address bar fix
  src/svelte/src/components/dataEditor.svelte
  src/svelte/src/utilities/display.ts
Labels: bug, javascript, typescript

#502 fix save over original file (fixes #501)
  src/omega_edit/dataEditWebView.ts
Labels: bug, typescript

#504 Naming cleanup and remove OmegaEdit version command
  package.json
  src/omega_edit/client.ts
  src/svelte/src/components/dataEditor.svelte
  src/tests/suite/dataEditor.test.ts
Labels: documentation

#506 alternative binary byte/bit indexing display
  src/svelte/src/utilities/display.ts
Labels: documentation, typescript

#510 Tab name to be the filepath of the file being edited
  src/omega_edit/dataEditWebView.ts
Labels: documentation, typescript

#511 move error msg and add instrux in edit vpt in single byte mode
  src/svelte/src/components/dataEditor.svelte
Labels: documentation, typescript

#515 Implement management for selected data.
  src/svelte/src/components/dataEditor.svelte
  src/svelte/src/stores/index.ts
Labels: bug, typescript

#508 CI updates
  .github/workflows/CI.yml
Labels: bug, CI

#524 Removed Duplicate Infotext & Reverted Editor div to textarea
  src/svelte/src/components/dataEditor.svelte
Labels: bug, typescript, data editor

#529 Reordered OE server kill & added verbose vars
  package.json
  src/omega_edit/client.ts
  src/omega_edit/dataEditWebView.ts
  src/svelte/src/components/dataEditor.svelte
Labels: bug, typescript, data editor

#535 Pin package rollup-plugin-multi-input to 1.3.2
  src/svelte/package.json
  src/svelte/yarn.lock
Labels: dependencies, build, CI

#525 add logic to handle tag attributes split on multiple lines
  src/language/dfdl.ts
  src/language/providers/attributeCompletion.ts
  src/language/providers/closeElement.ts
  src/language/providers/closeElementSlash.ts
  src/language/providers/closeUtils.ts
  src/language/providers/elementCompletion.ts
  src/language/providers/endSingleBrace.ts
  src/language/providers/intellisense/attributeItems.ts
  src/language/providers/intellisense/elementItems.ts
  src/language/providers/utils.ts
  src/tests/suite/language/items.test.ts
Labels: bug, typescript, code completion

#533 Data View offset displays in correct radix
  src/svelte/src/components/dataEditor.svelte
  src/svelte/src/stores/index.ts
Labels: bug, typescript, data editor

#534 Updated byte symbol for undefinedCharStandIn
  src/omega_edit/utils.ts
Labels: bug, typescript, data editor

#540 Update build.sbt to not duplicate compile/test aritfacts and get rid …
  .github/workflows/CI.yml
  build.sbt
  server/core/src/main/resources/bindings.xjb
Labels: bug, build, CI

#544 Adjusted file metrics fieldset for long file paths
  src/svelte/src/components/dataEditor.svelte
Labels: typescript, data editor
