Repository apache/daffodil-vscode, pull requests merged in 2023-01, with the labels that each got.

#407 allow self-signed certs when downloading test files over https (#405)
  .github/workflows/CI.yml
  .github/workflows/nightly.yml
  package.json
  src/tests/runTest.ts
  yarn.lock
Labels: testing, javascript, typescript

#414 Node and Scala Package updates
  .github/dependabot.yml
  .github/workflows/scala-steward.yml
  .scalafmt.conf
  build.sbt
  package.json
  project/Rat.scala
  project/build.properties
  project/plugins.sbt
  server/core/src/main/scala/org.apache.daffodil.debugger.dap/DAPodil.scala
  server/core/src/main/scala/org.apache.daffodil.debugger.dap/Parse.scala
  server/core/src/main/scala/org.apache.daffodil.debugger.dap/logging.scala
  src/tests/runTest.ts
  yarn.lock
Labels: dependencies, scala, typescript

#424 Update README.md
  README.md
Labels: documentation

#402 Launch Wizard - Daffodil Debugger Classpath manipulation
  src/launchWizard/launchWizard.js
  src/launchWizard/launchWizard.ts
  src/styles/styles.css
Labels: enhancement, typescript
