Repository apache/daffodil-vscode, pull requests merged in 2023-02, with the labels that each got.

#442 Remove no longer needed dependencies
  build/package/LICENSE
  build/package/NONOTICE
  package.json
  yarn.lock
Labels: dependencies, typescript

#440 Update omega-edit to allow configuration of the server port.
  .gitignore
  build/package/.vscodeignore
  package.json
  src/omega_edit/client.ts
  src/omega_edit/utils.ts
  src/tests/suite/omegaEdit.test.ts
  src/utils.ts
  yarn.lock
Labels: enhancement, typescript

#446 upgrade omega-edit from 0.9.33 to 0.9.34
  package.json
  yarn.lock
Labels: dependencies

#441 Update package names
  build/package/LICENSE
  package.json
  src/adapter/daffodilDebug.ts
  src/tests/suite/adapter.test.ts
  yarn.lock
Labels: dependencies, typescript

#449 update omega-edit from 0.9.34 to 0.9.39 for an important fixes
  package.json
  yarn.lock
Labels: bug, dependencies

#450 Upgrade OmegaEdit to v0.9.40 for TS declarations
  package.json
  yarn.lock
Labels: dependencies

#454 Upgrade Omega Edit to 0.9.41
  package.json
  yarn.lock
Labels: dependencies

#448 Update LICENSE, NONOTICE and remove NOLICENSE
  build/package/LICENSE
  build/package/NOLICENSE
  build/package/NONOTICE
  build/package/NOTICE
Labels: legal
