Repository apache/daffodil-vscode, pull requests merged in 2023-11, with the labels that each got.

#875 Add -no-header flag for consistent JAXB builds
  build.sbt
Labels: build

#894 Multiple CI updates
  .github/workflows/CI.yml
  .github/workflows/nightly.yml
Labels: CI

#896 Update NONOTICE and NOTICE
  build/package/NONOTICE
  build/package/NOTICE
  package.json
Labels: legal

#897 Fix check for using default values
  src/utils.ts
Labels: bug
