Repository apache/daffodil-vscode, pull requests merged in 2024-03, with the labels that each got.

#991 More helpful error messages
  debugger/src/main/scala/org.apache.daffodil.debugger.dap/DAPodil.scala
  debugger/src/main/scala/org.apache.daffodil.debugger.dap/ErrorEvent.scala
  src/adapter/activateDaffodilDebug.ts
  src/adapter/daffodilEvent.ts
Labels: debugger

#992 Launch configuration wizard mismatched label/text
  src/infoset.ts
  src/launchWizard/launchWizard.ts
Labels: configuration

#993 Omega Edit status messages must be in tolerance
  src/svelte/src/components/ServerMetrics/ServerMetrics.svelte
Labels: bug, data editor
