Repository apache/daffodil-vscode, pull requests merged in 2024-05, with the labels that each got.

#1020 Resolved Selection Highlighting Rescend
  src/svelte/src/utilities/highlights.ts
Labels: bug, typescript, data editor

#1016 fix save segment dialog (#1012)
  src/dataEditor/dataEditorClient.ts
  src/svelte/src/components/ServerMetrics/ServerMetrics.svelte
Labels: bug, typescript, data editor

#1026 fix prettier formatting in ServerMetrics.svelte (#1025)
  src/svelte/src/components/ServerMetrics/ServerMetrics.svelte
Labels: typescript, code quality, data editor

#1033 Nightly tests updates:
  .github/workflows/nightly.yml
Labels: build, CI

#1022 Fix broken TDML append, copy and execute functionality
  debugger/src/main/scala/org.apache.daffodil.tdml/TDML.scala
  debugger/src/test/scala/org.apache.daffodil.tdml/TDMLSuite.scala
  package.json
  src/adapter/activateDaffodilDebug.ts
  src/daffodilDebugger/debugger.ts
  src/tdmlEditor/utilities/tdmlXmlUtils.ts
  src/tests/suite/tdmlXmlUtils.test.ts
Labels: bug, TDML
