Repository apache/daffodil-vscode, pull requests merged in 2024-10, with the labels that each got.

#1107 Fixes intellisense problems discovered in RC1
  src/language/providers/attributeCompletion.ts
  src/language/providers/attributeValueCompletion.ts
  src/language/providers/closeElement.ts
  src/language/providers/closeElementSlash.ts
  src/language/providers/closeUtils.ts
  src/language/providers/elementCompletion.ts
  src/language/providers/intellisense/attributeHoverItems.ts
  src/language/providers/intellisense/attributeItems.ts
  src/language/providers/intellisense/attributeValueItems.ts
  src/language/providers/intellisense/elementItems.ts
  src/language/providers/utils.ts
  src/tests/suite/language/items.test.ts
Labels: bug, code completion

#1116 Update nightly tests to not run newer versions of VSCode on Windows
  .github/workflows/nightly.yml
Labels: CI

#1119 Upgrade Ωedit to solve DE startup problem under Windows (#1117)
  .github/workflows/CI.yml
  .github/workflows/nightly.yml
  package.json
Labels: bug, typescript, CI, data editor
