Repository apache/daffodil-vscode, pull requests merged in 2025-07, with the labels that each got.

#1310 Upgrade omegaEdit to 0.9.88 and add more detailed message regarding u…
  package.json
  src/dataEditor/dataEditorClient.ts
  yarn.lock
Labels: bug

#1259 Create dropdown menu for user to select test case name and descriptio…
  src/adapter/activateDaffodilDebug.ts
  src/utils.ts
Labels: enhancement, TDML

#1305 DFDL-1104
  src/styles/styles.css
Labels: bug, debugger

#1319 Intellisense: Don't suggest attributes if they already exist in an el…
  src/language/providers/attributeCompletion.ts
Labels: enhancement, code completion
