Repository apache/daffodil-vscode, pull requests merged in 2025-03, with the labels that each got.

#1189 Use ubuntu-22.04 for CI workflows.
  .github/workflows/CI.yml
  .github/workflows/nightly.yml
  .github/workflows/scala-steward.yml
Labels: CI

#1181 Added retainContextWhenHidden settings to fix the launch config reset…
  src/launchWizard/launchWizard.ts
  src/launchWizard/script.js
Labels: bug, configuration

#1178 Upgrade Ωedit to v0.9.87 (fixes #1128)
  package.json
  src/dataEditor/dataEditorClient.ts
  src/tests/runTest.ts
  yarn.lock
Labels: bug, dependencies, data editor

#1202 Update to Apache Daffodil 3.10.0
  debugger/src/main/scala/org.apache.daffodil.debugger.dap/Parse.scala
  package.json
Labels: dependencies, configuration

#1205 Added .xml extension after .prev to be recognized as an xml file
  src/adapter/daffodilEvent.ts
  src/infoset.ts
Labels: bug, configuration

#1197 Fix to remove dfdl prefix for dfdl attributes if the element containi…
  src/language/providers/attributeCompletion.ts
  src/language/providers/attributeHover.ts
  src/language/providers/attributeValueCompletion.ts
  src/language/providers/closeElement.ts
  src/language/providers/closeElementSlash.ts
  src/language/providers/closeUtils.ts
  src/language/providers/elementCompletion.ts
  src/language/providers/intellisense/elementItems.ts
  src/language/providers/utils.ts
  src/tests/DfdlIntellisenseTestingChecklist.md
  src/tests/README.md
  src/tests/data/helloWorldPlusLongForm.dfdl.xsd
  src/tests/data/testDfdlMixedLineFormats.dfdl.xsd
Labels: typescript, code completion, extension
