Repository apache/daffodil-vscode, pull requests merged in 2025-09, with the labels that each got.

#1363 Updated Readme file and added change log
  CHANGELOG.md
  README.md
  images/DE-brief.png
  images/asf_logo_url.png
  images/data-parse-debugger.png
  images/schema-dev.png
  project/Rat.scala
Labels: documentation

#1407 Add the ability to trigger CI with a PR number
  .github/workflows/CI.yml
  .github/workflows/licenes.yml
  .github/workflows/nightly.yml
  .github/workflows/release-candidate.yml
Labels: CI

#1408 Use correct secrets to deploy release candidates to nexus
  .github/workflows/release-candidate.yml
Labels: build, CI

#1410 Make it clear that the output stream chunk is 4KB in Parse.scala
  debugger/src/main/scala/org.apache.daffodil.debugger.dap/Parse.scala
Labels: documentation, scala, code quality

#1417 Fixed formatting and typo errors, added fontmatters and updated commit…
  .github/ISSUE_TEMPLATE/Bug_Report.md
  .github/ISSUE_TEMPLATE/Enhancement_Request.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/workflows/CI.yml
  .github/workflows/documentaion.yml
  .github/workflows/licenes.yml
  .github/workflows/nightly.yml
  .github/workflows/scala-steward.yml
  project/Rat.scala
Labels: code quality

#1375 Fix Visibility/Enablement for Extension Commands and Unify Conditions
  build/package/LICENSE
  package.json
  src/tests/suite/daffodil.test.ts
  src/views/commands.ts
  yarn.lock
Labels: enhancement, typescript, code quality, configuration

#1388 Make tdmlConfig.path always use default value for generate
  src/daffodilDebugger/debugger.ts
Labels: TDML, configuration
